Sources/Yj.Web/Controllers/DutyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Yj.Biz;
using Yj.Models;
using Webdiyer.WebControls.Mvc;

namespace Yj.Web.Controllers
{
    public class DutyController : BaseAuthorizeController
    {
        /// <summary>
        /// 系统角色
        /// </summary>
        /// <param name="model"></param>
        /// <param name="isSearch"></param>
        /// <returns></returns>
        public ActionResult Index(ls_duty model, string isSearch)
        {
            int pageIndex = 1;

            PagedList<ls_duty> pagerModel = GetUsers(model, pageIndex);

            //返回数据
            if (!string.IsNullOrWhiteSpace(isSearch) && isSearch == "1")
            {
                return PartialView("DutyListPartial", pagerModel);
            }

            return View(pagerModel);
        }

        /// <summary>
        /// 系统角色
        /// </summary>
        /// <param name="model"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(ls_duty model, int? page = 1)
        {
            int pageIndex = page ?? 1;

            PagedList<ls_duty> pagerModel = GetUsers(model, pageIndex);

            return PartialView("DutyListPartial", pagerModel);
        }

        /// <summary>
        /// 获取角色数据
        /// </summary>
        /// <returns></returns>
        private PagedList<ls_duty> GetUsers(ls_duty model, int pageIndex)
        {
            int totalRow = 0;
            int pageSize = Common.Config.PageSize;

            PagedList<ls_duty> pagerModel = ls_dutyBiz.Instance.GetList(model, pageIndex - 1, pageSize, out totalRow).AsQueryable().ToPagedList(1, pageSize);

            if (pagerModel != null)
            {
                pagerModel.TotalItemCount = totalRow;
                pagerModel.CurrentPageIndex = pageIndex;
            }

            return pagerModel;
        }

        /// <summary>
        /// 修改角色信息
        /// </summary>
        /// <param name="duty_id"></param>
        /// <returns></returns>
        public ActionResult EditDuty(int? duty_id)
        {
            ls_duty model = new ls_duty { duty_id = 0 };

            if (duty_id != null)
            {
                model = Biz.ls_dutyBiz.Instance.GetModelById(duty_id.Value);
            }

            return View(model);
        }

        /// <summary>
        /// 修改角色信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditDuty(ls_duty model)
        {
            // 无需验证的字段
            //ModelState.Remove("user_old_password");

            bool result = false;

            Common.JsonData<ls_duty> data = new Common.JsonData<ls_duty>
            {
                Message = "操作失败！"
            };

            // 验证是否全部通过
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    if (!string.IsNullOrEmpty(Request.QueryString["duty_id"]))
                    {
                        // 修改用户信息
                        result = Biz.ls_dutyBiz.Instance.EditModel(model);

                        if (result)
                        {
                            data.Message = "修改角色成功！";
                        }
                    }
                    else
                    {
                        // 添加用户信息
                        result = Biz.ls_dutyBiz.Instance.AddModel(model);

                        if (result)
                        {
                            data.Message = "添加角色成功！";
                        }
                    }
                }
            }

            data.Flag = result;

            return Json(data);
        }

        /// <summary>
        /// 删除角色
        /// </summary>
        /// <param name="duty_id"></param>
        /// <returns></returns>
        [HttpPost]
        public bool DeleteDuty(int? duty_id)
        {
            bool result = false;

            if (duty_id != null)
            {
                result = Biz.ls_dutyBiz.Instance.Delete(duty_id.Value);
            }

            return result;
        }

        /// <summary>
        /// 角色名是否存在
        /// </summary>
        /// <returns></returns>
        public ActionResult IsExistDutyName(int duty_id, string duty_name)
        {
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 角色权限编辑
        /// </summary>
        /// <param name="duty_id"></param>
        /// <returns></returns>
        public ActionResult DutyModule(int? duty_id)
        {
            // 分类
            List<string> categories = new List<string>();

            // 模块和权限信息
            List<CheckBoxObject> objs = new List<CheckBoxObject>();

            if (duty_id != null)
            {
                // 用户所拥有的模块和权限
                List<ls_duty_module> duty_modules = Biz.ls_duty_moduleBiz.Instance.GetList(duty_id.Value).ToList();

                ls_duty model = Biz.ls_dutyBiz.Instance.GetModelById(duty_id.Value);

                // 获取所有Modules
                List<ls_module> modules = Biz.ls_moduleBiz.Instance.GetList().ToList();

                // 权限信息
                foreach (var category in modules.Where(m => !string.IsNullOrEmpty(m.module_category)).Select(m => m.module_category).Distinct())
                {
                    categories.Add(Biz.Cache.CommonCache.GetModuleCategory(category));

                    // 模块和权限信息
                    foreach (var module in modules.Where(m => m.module_category == category))
                    {
                        CheckBoxObject obj = new CheckBoxObject
                        {
                            Title = module.module_name,
                            Text = module.module_name,
                            Value = module.module_id.ToString()
                        };

                        if (!string.IsNullOrEmpty(module.module_roles))
                        {
                            string[] role_codes = module.module_roles.Split(',').Where(m => !string.IsNullOrEmpty(m)).ToArray();

                            if (role_codes != null && role_codes.Count() > 0)
                            {
                                obj.Datas = new List<SelectListItem>();

                                foreach (var code in role_codes)
                                {
                                    List<ls_role> roles = Biz.Cache.CommonCache.Roles;

                                    ls_role role = roles.Where(r => r.role_code == code).FirstOrDefault();

                                    if (role != null && !string.IsNullOrEmpty(role.role_name))
                                    {
                                        SelectListItem item = new SelectListItem { Text = role.role_name, Value = role.role_code, Selected = false };

                                        if (duty_modules != null && duty_modules.Count > 0)
                                        {
                                            // 判断是否选择
                                            ls_duty_module duty_module = duty_modules.Where(dm => dm.module_id == module.module_id).FirstOrDefault();

                                            if (duty_module != null && duty_module.duty_module_roles.Contains(role.role_code))
                                            {
                                                item.Selected = true;
                                            }
                                        }

                                        obj.Datas.Add(item);
                                    }
                                }

                                objs.Add(obj);
                            }
                        }
                    }
                }

                ViewBag.Categories = categories;
                ViewBag.CheckBoxDatas = objs;

                if (model == null)
                {
                    model = new ls_duty { duty_id = 0 };
                }

                return View(model);
            }

            return Content("参数有误");
        }

        /// <summary>
        /// 角色权限编辑
        /// </summary>
        /// <param name="duty_id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DutyModule(ls_duty model, string[] modules, string[] duty_roles)
        {
            // 无需验证的字段
            //ModelState.Remove("user_old_password");

            bool result = false;

            Common.JsonData<ls_duty_module> data = new Common.JsonData<ls_duty_module>
            {
                Message = "操作失败！"
            };

            // 验证是否全部通过
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    // 删除角色所有的模块
                    if (Biz.ls_duty_moduleBiz.Instance.Delete(model.duty_id))
                    {
                        List<int> duty_modules = new List<int>();

                        foreach (var duty_role in duty_roles.Where(r => !string.IsNullOrEmpty(r)))
                        {
                            string[] module_roles = duty_role.Split('_').Where(r => !string.IsNullOrEmpty(r)).ToArray();

                            int module_id = 0;

                            if (module_roles != null && module_roles.Count() == 2 && int.TryParse(module_roles[0], out module_id))
                            {
                                duty_modules.Add(module_id);
                            }
                        }


Sources/Yj.Web/Views/Duty/DutyListPartial.cshtml
@model PagedList<Yj.Models.ls_duty>
@using Webdiyer.WebControls.Mvc;
<div id="gridTable">
    <table class="table table-border table-bordered table-bg">
        <thead>
            <tr>
                <th scope="col" colspan="9">角色列表</th>
            </tr>
            <tr class="text-c">
                <th width="25">
                    <input type="checkbox" name="" value=""></th>
                <th>角色名</th>
                <th>描述</th>
                <th width="160">操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Yj.Models.ls_duty duty in Model)
            {
                <tr class="text-c">
                    <td>
                        <input type="checkbox" value="@duty.duty_id" name="">
                    </td>
                    <td>@duty.duty_name</td>
                    <td>@duty.description</td>
                    <td>
                        <a href="javascript:;" onclick="edit_duty('编辑角色','/Duty/EditDuty?duty_id=@duty.duty_id','800','320')"><i class="Hui-iconfont" title="编辑"></i></a>
                        &nbsp;&nbsp;|&nbsp;&nbsp;<a id="delete" href="javascript:del_duty('@duty.duty_id');"><i class="Hui-iconfont" title="删除"></i></a>
                        &nbsp;&nbsp;|&nbsp;&nbsp;<a id="modify_role" href="javascript:duty_role_edit('角色权限编辑', '/Duty/DutyModule?duty_id=@duty.duty_id');">修改权限</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.AjaxPager(Model,
    new PagerOptions
    {
        Id = "pager",
        CssClass = "pager",
        PageIndexParameterName = "page",
        ShowPageIndexBox = true,
        FirstPageText = "首页",
        PrevPageText = "上一页",
        NextPageText = "下一页",
        LastPageText = "末页",
        PageIndexBoxType = PageIndexBoxType.TextBox,
        PageIndexBoxWrapperFormatString = "请输入页数{0}",
        GoButtonText = "转到"
    },
    new AjaxOptions
    {
        HttpMethod = "Post",
        UpdateTargetId = "gridTable"
    })
</div>

Sources/Yj.Web/Views/Duty/DutyModule.cshtml
@model Yj.Models.ls_duty
@{
    ViewBag.Title = string.Format("角色权限修改 - {0}", Yj.Common.Config.WebTitle);
}
<div class="page-container" id="edit">
    @using (Ajax.BeginForm("DutyModule", "Duty", new { duty_id = Request.QueryString["duty_id"] }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "edit", OnSuccess = "OnSuccess" }, new { @class = "form form-horizontal", id = "form-article-add" }))
    {
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2"><span class="c-red">*</span>角色名：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.HiddenFor(m => m.duty_id)
                @Html.TextBoxFor(m => m.duty_name, new { @class = "input-text", style = "width: 360px", @readonly = "readonly" })
                @Html.ValidationMessageFor(m => m.duty_name)
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2">权限：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.CheckBoxList("modules", "duty_roles", ViewBag.Categories as List<string>, ViewBag.CheckBoxDatas as List<CheckBoxObject>)
            </div>
        </div>
        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-2">
                <button class="btn btn-primary radius" type="submit"><i class="Hui-iconfont">&#xe632;</i> 确定</button>
                <button onclick="layer_close();" class="btn btn-default radius" type="button">&nbsp;&nbsp;取消&nbsp;&nbsp;</button>
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="/Content/lib/micro/jquery.validate.min.js"></script>
<script type="text/javascript" src="/Content/lib/micro/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    // 执行成功时，关闭layer，刷新后面的列表
    function OnSuccess(data) {
        // 提示信息
        layer.msg(data.Message, { icon: 1, time: 1000 });
        // 刷新后面的列表
        if (String(data.Flag).toLowerCase() == 'true') {
            // 父页面必须写reloadData函数
            window.parent.reloadData();
        }
        // 关闭弹出框
        delay_layer_close(1000);
    }

    // 页面加载后
    $(function () {
        // 选择所有
        $('.select_all').click(function () {
            $(this).parent().parent().next().find('input[type=checkbox]').prop('checked', $(this).prop('checked'));
        });

        // 选择当前行所有
        $('.select_item_all').click(function () {
            $(this).parent().parent().next().find('input[type=checkbox]').prop('checked', $(this).prop('checked'));
        });
    });
</script>

Sources/Yj.Web/Views/Duty/EditDuty.cshtml
@model Yj.Models.ls_duty
@{
    ViewBag.Title = string.Format("添加角色 - {0}", Yj.Common.Config.WebTitle);
}
<div class="page-container" id="edit">
    @using (Ajax.BeginForm("EditDuty", "Duty", new { duty_id = Request.QueryString["duty_id"] }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "edit", OnSuccess = "OnSuccess" }, new { @class = "form form-horizontal", id = "form-article-add" }))
    {
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2"><span class="c-red">*</span>角色名：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.HiddenFor(m => m.duty_id)
                @Html.TextBoxFor(m => m.duty_name, new { @class = "input-text", style = "width: 360px" })
                @Html.ValidationMessageFor(m => m.duty_name)
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2">描述：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.TextAreaFor(m => m.description, new { @class = "textarea", placeholder = "说点什么...", style = "width: 360px", onkeyup = "textarealength(this,200)" })
                @Html.ValidationMessageFor(m => m.description)
                <p class="textarea-numberbar"><em class="textarea-length">0</em>/200</p>
            </div>
        </div>
        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-2">
                <button class="btn btn-primary radius" type="submit"><i class="Hui-iconfont">&#xe632;</i> 确定</button>
                <button onclick="layer_close();" class="btn btn-default radius" type="button">&nbsp;&nbsp;取消&nbsp;&nbsp;</button>
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="/Content/lib/micro/jquery.validate.min.js"></script>
<script type="text/javascript" src="/Content/lib/micro/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    // 执行成功时，关闭layer，刷新后面的列表
    function OnSuccess(data) {
        // 提示信息
        layer.msg(data.Message, { icon: 1, time: 1000 });
        // 刷新后面的列表
        if (String(data.Flag).toLowerCase() == 'true') {
            // 父页面必须写reloadData函数
            window.parent.reloadData();
        }
        // 关闭弹出框
        delay_layer_close(1000);
    }
</script>

Sources/Yj.Web/Views/Duty/Index.cshtml
@{
    ViewBag.Title = string.Format("角色管理 - {0}", Yj.Common.Config.WebTitle);
}
<nav class="breadcrumb">
    <i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 角色管理 <span class="c-gray en">&gt;</span> 角色列表
    <a class="btn btn-success radius r" style="line-height: 1.6em; margin-top: 3px" href="javascript:location.replace(location.href);" title="刷新"><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<div class="page-container">
    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "gridTable" }))
    {
        <div class="text-c">
            <input type="text" class="input-text" style="width: 250px" placeholder="输入角色名称" id="duty_name" name="duty_name">
            <input type="hidden" id="isSearch" name="isSearch" value="1" />
            <button type="submit" class="btn btn-success" id="btnSearch" name=""><i class="Hui-iconfont">&#xe665;</i> 搜角色</button>
        </div>
    }
    <div class="cl pd-5 bg-1 bk-gray mt-20">
        <span class="l">
            <a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a>
            <a href="javascript:;" onclick="edit_duty('添加角色','/Duty/EditDuty','800','320')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加角色</a>
        </span>
    </div>
    @Html.Partial("DutyListPartial")
</div>
<script type="text/javascript">
    // 刷新列表
    function reloadData() {
        $('#btnSearch').click();
    }

    /*
        参数解释：
        title	标题
        url		请求的url
        id		需要操作的数据id
        w		弹出层宽度（缺省调默认值）
        h		弹出层高度（缺省调默认值）
    */
    /*管理员-增加*/
    function edit_duty(title, url, w, h) {
        layer_show(title, url, w, h);
    }
    /*管理员-删除*/
    function del_duty(id) {
        if (!isNullOrEmpty(id)) {
            layer.confirm('确认要删除吗？', function (index) {
                // 删除角色
                $.ajax({
                    type: 'Post',
                    url: '/Duty/DeleteDuty',
                    data: { duty_id: id },
                    dataType: 'text', // 返回数据格式
                    success: function (data) {
                        if (data.toLowerCase() == 'true') {
                            layer.msg('删除成功!', { icon: 1, time: 1000 });
                            $('#btnSearch').click();
                        }
                        else {
                            layer.msg('删除失败!', { icon: 1, time: 1000 });
                        }
                    }
                });
            });
        }
    }
    /*管理员-批量删除*/
    function datadel() {
        layer.msg('该功能暂未开通!', { icon: 1, time: 1000 });
    }
    /*角色权限-编辑*/
    function duty_role_edit(title, url) {
        var index = layer.open({
            type: 2,
            title: title,
            content: url
        });
        layer.full(index);
    }
</script>