Sources/Yj.Web/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using Yj.Biz;
using Yj.Models;
using Webdiyer.WebControls.Mvc;

namespace Yj.Web.Controllers
{
    public class ModuleController : BaseAuthorizeController
    {
        /// <summary>
        /// 系统模块
        /// </summary>
        /// <param name="model"></param>
        /// <param name="isSearch"></param>
        /// <returns></returns>
        public ActionResult Index(ls_module model, string isSearch)
        {
            int pageIndex = 1;

            PagedList<ls_module> pagerModel = GetModules(model, pageIndex);

            //返回数据
            if (!string.IsNullOrWhiteSpace(isSearch) && isSearch == "1")
            {
                return PartialView("ModuleListPartial", pagerModel);
            }

            return View(pagerModel);
        }

        /// <summary>
        /// 系统模块
        /// </summary>
        /// <param name="model"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(ls_module model, int? page = 1)
        {
            int pageIndex = page ?? 1;

            PagedList<ls_module> pagerModel = GetModules(model, pageIndex);

            return PartialView("ModuleListPartial", pagerModel);
        }

        /// <summary>
        /// 获取模块数据
        /// </summary>
        /// <returns></returns>
        private PagedList<ls_module> GetModules(ls_module model, int pageIndex)
        {
            int totalRow = 0;
            int pageSize = Common.Config.PageSize;

            PagedList<ls_module> pagerModel = ls_moduleBiz.Instance.GetList(model, pageIndex - 1, pageSize, out totalRow).AsQueryable().ToPagedList(1, pageSize);

            if (pagerModel != null)
            {
                pagerModel.TotalItemCount = totalRow;
                pagerModel.CurrentPageIndex = pageIndex;
            }

            return pagerModel;
        }

        /// <summary>
        /// 修改模块信息
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public ActionResult EditModule(int? module_id)
        {
            ls_module model = new ls_module { module_id = 0 };

            if (module_id != null)
            {
                model = Biz.ls_moduleBiz.Instance.GetModelById(module_id.Value);
            }

            // 系统分类
            List<SelectListItem> items = new List<SelectListItem> { new SelectListItem { Text = "-- 请选择 --" } };

            foreach (var item in Biz.Cache.CommonCache.ModuleCategories)
            {
                items.Add(new SelectListItem { Text = item.Value, Value = item.Key });
            }

            ViewBag.ModuleCategories = items;

            // 权限信息
            // 分类
            List<string> categories = new List<string> { "模块权限" };
            ViewBag.Categories = categories;

            // 权限信息
            List<CheckBoxObject> objs = new List<CheckBoxObject>();

            // 获取所有权限信息
            List<ls_role> roles = Biz.Cache.CommonCache.Roles;

            CheckBoxObject obj = new CheckBoxObject
            {
                Title = ""
            };

            if (roles != null)
            {
                obj.Datas = new List<SelectListItem>();

                foreach (ls_role role in roles.OrderBy(r => r.role_id))
                {
                    SelectListItem item = new SelectListItem
                    {
                        Text = role.role_name,
                        Value = role.role_code,
                        Selected = false
                    };

                    if (model != null && !string.IsNullOrEmpty(model.module_roles) && model.module_roles.Contains(role.role_code))
                    {
                        item.Selected = true;
                    }

                    obj.Datas.Add(item);
                }
            }

            objs.Add(obj);

            ViewBag.CheckBoxDatas = objs;

            return View(model);
        }

        /// <summary>
        /// 修改模块信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditModule(ls_module model, string[] modules, string[] module_roles)
        {
            // 无需验证的字段
            //ModelState.Remove("user_old_password");

            bool result = false;

            Common.JsonData<ls_module> data = new Common.JsonData<ls_module>
            {
                Message = "操作失败！"
            };

            // 验证是否全部通过
            if (ModelState.IsValid)
            {
                if (model != null)
                {
                    if (module_roles != null && module_roles.Count() > 0)
                    {
                        model.module_roles = string.Join(",", module_roles);
                    }

                    if (!string.IsNullOrEmpty(Request.QueryString["module_id"]))
                    {
                        // 修改模块信息
                        result = Biz.ls_moduleBiz.Instance.EditModel(model);

                        if (result)
                        {
                            data.Message = "修改模块成功！";
                        }
                    }
                    else
                    {
                        // 添加模块信息
                        result = Biz.ls_moduleBiz.Instance.AddModel(model);

                        if (result)
                        {
                            data.Message = "添加模块成功！";
                        }
                    }
                }
            }

            data.Flag = result;

            return Json(data);
        }

        /// <summary>
        /// 删除模块
        /// </summary>
        /// <param name="module_id"></param>
        /// <returns></returns>
        [HttpPost]
        public bool DeleteModule(int? module_id)
        {
            bool result = false;

            if (module_id != null)
            {
                result = Biz.ls_moduleBiz.Instance.Delete(module_id.Value);
            }

            return result;
        }

        /// <summary>
        /// 模块名是否存在
        /// </summary>
        /// <returns></returns>
        public ActionResult IsExistModuleName(int module_id, string role_name)
        {
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Sources/Yj.Web/Views/Module/EditModule.cshtml
@model Yj.Models.ls_module
@{
    ViewBag.Title = string.Format("添加模块 - {0}", Yj.Common.Config.WebTitle);
}
<div class="page-container" id="edit">
    @using (Ajax.BeginForm("EditModule", "Module", new { module_id = Request.QueryString["module_id"] }, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "edit", OnSuccess = "OnSuccess" }, new { @class = "form form-horizontal", id = "form-article-add" }))
    {
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2"><span class="c-red">*</span>模块分类：</label>
            <div class="formControls col-xs-8 col-sm-9">
                <span class="select-box" style="width: 360px; padding-left: 0px;">
                    @Html.DropDownListFor(m => m.module_category, ViewBag.ModuleCategories as List<SelectListItem>, new { @class = "select", style = "width: 355px" })
                </span>
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2"><span class="c-red">*</span>模块名：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.HiddenFor(m => m.module_id)
                @Html.TextBoxFor(m => m.module_name, new { @class = "input-text", style = "width: 360px" })
                @Html.ValidationMessageFor(m => m.module_name)
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2"><span class="c-red">*</span>路径：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.TextBoxFor(m => m.module_path, new { @class = "input-text", style = "width: 360px" })
                @Html.ValidationMessageFor(m => m.module_path)
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-xs-4 col-sm-2">权限：</label>
            <div class="formControls col-xs-8 col-sm-9">
                @Html.CheckBoxList("modules", "module_roles", ViewBag.Categories as List<string>, ViewBag.CheckBoxDatas as List<CheckBoxObject>)
            </div>
        </div>
        <div class="row cl">
            <div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-2">
                <button class="btn btn-primary radius" type="submit"><i class="Hui-iconfont">&#xe632;</i> 确定</button>
                <button onclick="layer_close();" class="btn btn-default radius" type="button">&nbsp;&nbsp;取消&nbsp;&nbsp;</button>
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="/Content/lib/micro/jquery.validate.min.js"></script>
<script type="text/javascript" src="/Content/lib/micro/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    // 执行成功时，关闭layer，刷新后面的列表
    function OnSuccess(data) {
        // 提示信息
        layer.msg(data.Message, { icon: 1, time: 1000 });
        // 刷新后面的列表
        if (String(data.Flag).toLowerCase() == 'true') {
            // 父页面必须写reloadData函数
            window.parent.reloadData();
        }
        // 关闭弹出框
        delay_layer_close(1000);
    }

    // 页面加载后
    $(function () {
        // 选择所有
        $('.select_all').click(function () {
            $(this).parent().parent().next().find('input[type=checkbox]').prop('checked', $(this).prop('checked'));
        });
    });
</script>

Sources/Yj.Web/Views/Module/Index.cshtml
@{
    ViewBag.Title = string.Format("模块管理 - {0}", Yj.Common.Config.WebTitle);
}
<nav class="breadcrumb">
    <i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 模块管理 <span class="c-gray en">&gt;</span> 模块列表
    <a class="btn btn-success radius r" style="line-height: 1.6em; margin-top: 3px" href="javascript:location.replace(location.href);" title="刷新"><i class="Hui-iconfont">&#xe68f;</i></a>
</nav>
<div class="page-container">
    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "gridTable" }))
    {
        <div class="text-c">
            <input type="text" class="input-text" style="width: 250px" placeholder="输入模块名称" id="module_name" name="module_name">
            <input type="hidden" id="isSearch" name="isSearch" value="1" />
            <button type="submit" class="btn btn-success" id="btnSearch" name=""><i class="Hui-iconfont">&#xe665;</i> 搜模块</button>
        </div>
    }
    <div class="cl pd-5 bg-1 bk-gray mt-20">
        <span class="l">
            <a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a>
            <a href="javascript:;" onclick="edit_module('添加模块','/Module/EditModule','800','400')" class="btn btn-primary radius"><i class="Hui-iconfont">&#xe600;</i> 添加模块</a>
        </span>
    </div>
    @Html.Partial("ModuleListPartial")
</div>
<script type="text/javascript">
    // 刷新列表
    function reloadData() {
        $('#btnSearch').click();
    }

    /*
        参数解释：
        title	标题
        url		请求的url
        id		需要操作的数据id
        w		弹出层宽度（缺省调默认值）
        h		弹出层高度（缺省调默认值）
    */
    /*管理员-增加*/
    function edit_module(title, url, w, h) {
        layer_show(title, url, w, h);
    }
    /*管理员-删除*/
    function del_module(id) {
        if (!isNullOrEmpty(id)) {
            layer.confirm('确认要删除吗？', function (index) {
                // 删除模块
                $.ajax({
                    type: 'Post',
                    url: '/Module/DeleteModule',
                    data: { module_id: id },
                    dataType: 'text', // 返回数据格式
                    success: function (data) {
                        if (data.toLowerCase() == 'true') {
                            layer.msg('删除成功!', { icon: 1, time: 1000 });
                            $('#btnSearch').click();
                        }
                        else {
                            layer.msg('删除失败!', { icon: 1, time: 1000 });
                        }
                    }
                });
            });
        }
    }
    /*管理员-批量删除*/
    function datadel() {
        layer.msg('该功能暂未开通!', { icon: 1, time: 1000 });
    }
</script>

Sources/Yj.Web/Views/Module/ModuleListPartial.cshtml
@model PagedList<Yj.Models.ls_module>
@using Webdiyer.WebControls.Mvc;
<div id="gridTable">
    <table class="table table-border table-bordered table-bg">
        <thead>
            <tr>
                <th scope="col" colspan="9">模块列表</th>
            </tr>
            <tr class="text-c">
                <th width="25">
                    <input type="checkbox" name="" value=""></th>
                <th>模块分类</th>
                <th>模块名</th>
                <th>路径</th>
                <th width="160">操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Yj.Models.ls_module module in Model)
            {
                <tr class="text-c">
                    <td>
                        <input type="checkbox" value="@module.module_id" name="">
                    </td>
                    <td>@Yj.Biz.Cache.CommonCache.GetModuleCategory(module.module_category)</td>
                    <td>@module.module_name</td>
                    <td>@module.module_path</td>
                    <td>
                        <a href="javascript:;" onclick="edit_module('编辑权限','/Module/EditModule?module_id=@module.module_id','800','400')"><i class="Hui-iconfont" title="编辑"></i></a>
                        &nbsp;&nbsp;|&nbsp;&nbsp;<a id="delete" href="javascript:del_module('@module.module_id');"><i class="Hui-iconfont" title="删除"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.AjaxPager(Model,
    new PagerOptions
    {
        Id = "pager",
        CssClass = "pager",
        PageIndexParameterName = "page",
        ShowPageIndexBox = true,
        FirstPageText = "首页",
        PrevPageText = "上一页",
        NextPageText = "下一页",
        LastPageText = "末页",
        PageIndexBoxType = PageIndexBoxType.TextBox,
        PageIndexBoxWrapperFormatString = "请输入页数{0}",
        GoButtonText = "转到"
    },
    new AjaxOptions
    {
        HttpMethod = "Post",
        UpdateTargetId = "gridTable"
    })
</div>